image: debian:testing

build:
  script:
    - apt-get -qq update
    - apt-get --assume-yes --no-install-recommends install cmake
    - apt-get --assume-yes --no-install-recommends install g++
    - apt-get --assume-yes --no-install-recommends install gcovr
    - apt-get --assume-yes --no-install-recommends install git
    - apt-get --assume-yes --no-install-recommends install make
    - apt-get --assume-yes --no-install-recommends install pipewire
    - apt-get --assume-yes --no-install-recommends install pipewire-pulse
    - apt-get --assume-yes --no-install-recommends install qt6-base-dev
    - apt-get --assume-yes --no-install-recommends install qt6-l10n-tools
    - apt-get --assume-yes --no-install-recommends install qt6-multimedia-dev
    - apt-get --assume-yes --no-install-recommends install qt6-tools-dev
    - apt-get --assume-yes --no-install-recommends install qt6-tools-dev-tools
    - apt-get --assume-yes --no-install-recommends install xauth
    - apt-get --assume-yes --no-install-recommends install xvfb
    - echo $CI_BUILDS_DIR
    - echo $CI_PROJECT_DIR
    - echo $HOME
    - pwd
    - mkdir $HOME/build
    - cd $HOME/build
    - pwd
    - cmake -DCMAKE_BUILD_TYPE=Debug $CI_PROJECT_DIR
    - make
    # - pipewire
    # - pipewire-pulse
    # - export CTEST_OUTPUT_ON_FAILURE=1
    # - xvfb-run ctest
    # - make coverage
    # - ls
