name: CI

on:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [x64]
        qt-version: ['6.2.4']
    steps:
    - uses: actions/checkout@v2
    - uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt-version }}
        modules: 'qtmultimedia qtcharts'
    - uses: seanmiddleditch/gha-setup-ninja@v3
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.platform }}
    - name: configure
      run: |
        INSTALL_PATH=app-target
        echo "INSTALL_PATH=$INSTALL_PATH" >>$GITHUB_ENV
        cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PATH -B build
    - name: build
      run: cmake --build build --target install
